ALTER TABLE events ADD COLUMN start_datetime TIMESTAMP NOT NULL;
ALTER TABLE events ADD COLUMN end_datetime TIMESTAMP NOT NULL;
ALTER TABLE events ADD COLUMN modtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE events ADD COLUMN calendar_description TEXT;
ALTER TABLE events ADD COLUMN calendar_uuid VARCHAR(36);
ALTER TABLE events ADD COLUMN location VARCHAR(128);
